version: 2
jobs:
  build:
    docker:
      - image:  cimg/python:3.8.10-node
    working_directory: ~/repo
    environment:
      BRANCH: develop
      TARGET_REPO: github.com/SaikrishnaBairamoni/saikrishnabairamoni.github.io
      PELICAN_OUTPUT_FOLDER: output
    steps:
      - checkout        
      - run:
          name: install doxygen latex components
          command: |
            #sudo apt-get update; sudo apt-get install -y doxygen graphviz texlive-full
            #sudo apt-get install git wget tar unzip cmake -y
            #sudo apt-get -y -qq update
            #sudo apt-get -y install build-essential checkinstall
            ls -la
            pwd         
            
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
           branches:
              ignore: gh-pages
           tags:
              only: /^[\.0-9]*$/
