version: 2
jobs:
  build:
    docker:
      - image:  cimg/python:3.8.10-node
    working_directory: ~/repo
    environment:
      BRANCH: develop
      TARGET_REPO: 
      PELICAN_OUTPUT_FOLDER: output
    steps:
      - checkout
